server:
  port: 18545
  servlet:
    context-path: /agrotis/cad
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_PROVIDER}
spring:
  profiles:
    active:
      - api-doc
  application:
    name: cad
  datasource:
    url: jdbc:postgresql://localhost:5433/enginedb
    username: postgres
    password: qa.4736
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com:
      ecwid.consul: OFF
    org:
      springframework:
        cloud: OFF
        security: INFO
  charset:
    console:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

agrotis:
  environment:
    server:
      dev-url: http://localhost:${server.port}${server.servlet.context-path}
      hml-url: http://hml:${server.port}${server.servlet.context-path}
      prd-url: http://prd:${server.port}${server.servlet.context-path}
